import Head from 'next/head';
import Image from 'next/image';
import ProductItem from '../components/ProductItem';
import PageDescription from '../components/PageDescription';
import StoreNavBar from '../components/StoreNavBar';
import { useRouter } from 'next/router';
import { useContext } from 'react';
import ItemsSelectedContext from '../context/itemsSelected-provider';
import styles from '@/styles/Home.module.css';
import { Inter } from 'next/font/google';
import { getProducts } from '@/api/products';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ products }) {

  const router = useRouter();
  const useItemsSelectedContext = useContext(ItemsSelectedContext);
  const { itemsList } = useItemsSelectedContext;
  //console.log(itemsList);
  const path = router.pathname;

  //console.log(router.pathname);


  return (
    <>
      <Head>
        <title>Repostería Ángeles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StoreNavBar itemsList={itemsList} />
      <main className={`${styles.main} ${inter.className}`}>
        <PageDescription title="Nuestros productos" />
        <section>
          {products.map((product) => (
            <ProductItem key={product._id} product={product} />
          ))}

        </section>
      </main>
    </>
  )
};

export async function getServerSideProps() {
  const products = await getProducts();


  return {
    props: {
      products,
    },
  };

};
