import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import ProductItem from './components/ProductItem';
import PageDescription from './components/PageDescription';
import StoreNavBar from './components/StoreNavBar';
import { useState } from 'react';
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] })

export default function Home({ products }) {
  const [itemsList, setItemList] = useState([]);
  const router = useRouter();

  console.log(router.pathname);

  const handleAddItem = (product) => {
    const items = itemsList;
    //console.log(product);
    setItemList([...items, product]);

  };
  return (
    <>
      <Head>
        <title>Repostería Ángeles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StoreNavBar itemsList={itemsList} />
      <main className={`${styles.main} ${inter.className}`}>
        <PageDescription title="Nuestros productos" />
        <section>
          {products.map((product) => (
            <ProductItem key={product._id} product={product} handleAddItem={handleAddItem} />
          ))}

        </section>
      </main>
    </>
  )
};

export async function getServerSideProps() {
  let products = [
    {
      _id: 1,
      name: "Babka de chocolate",
      description: "Pan trenzado relleno de chocolate",
      price: "230 MXP",
      imageUrl: "https://www.foodandwine.com/thmb/3alI1eL7tHTvNuAH9jQlHDDx2Yw=/1200x0/filters:no_upscale():max_bytes(150000):strip_icc()/RECIPE0116-XL-chocolate-babka-1a2e39def5f043f58caf48b97456a119.jpg"
    },
    {
      _id: 2,
      name: "Roles de canela",
      description: "Pan trenzado relleno de chocolate",
      price: "20 MXP",
      imageUrl: "https://www.savynaturalista.com/wp-content/uploads/Sugar-Free-Cinanamon-Rolls-6.jpg"
    },

  ];
  return {
    props: {
      products,
    },
  };

};
